config/routes.rb
Rails.application.routes.draw do
  get 'role/index'
  get 'role/show'
  get 'about/index'
  resources :welcome
  resources :heroes, only: [:index, :show] do
      collection do
        get "search"
      end
  end
  resources :primary_attribute, only: [:index, :show]
  resources :about
  resources :role, only: [:index, :show]

  root to:"welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hero.rb
class Hero < ApplicationRecord
  belongs_to :primary_attribute
  has_many :hero_roles
  has_many :roles, through: :hero_roles
  validates :name, :localized_name, :attack_type, :legs, presence: true
  validates :name, :localized_name, uniqueness:true
  validates :legs, numericality:{only_integer:true}

  def roles_list
      roles.map(&:name).join(", ")
  end
end

app/models/hero_role.rb
class HeroRole < ApplicationRecord
  belongs_to :hero
  belongs_to :role
end

app/models/primary_attribute.rb
class PrimaryAttribute < ApplicationRecord
  has_many :heroes

  validates :name, presence:true, uniqueness:true
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :hero_roles
  has_many :heroes, through: :hero_roles
  validates :name, presence: true, uniqueness:true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/heroes_controller.rb
class HeroesController < ApplicationController
  HERO_PER_PAGE = 10
  def index
    @page = params.fetch(:page, 0).to_i
    @heroes = Hero.offset(@page * HERO_PER_PAGE).limit(HERO_PER_PAGE)

  end
  #The @heroes variable will be share with:
  #app/voews/heroes/index.html.erb

  def show
    @hero =Hero.find(params[:id])
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"
    @heroes_searched = Hero.where("localized_name LIKE ?", wildcard_search)
  end
end

app/controllers/primary_attribute_controller.rb
class PrimaryAttributeController < ApplicationController
  def index
    @primary_attributes = PrimaryAttribute.all
    @agi_count = Hero.where("primary_attribute_id = ?", params[:id]).count
  end

  def show
    @hero_based_on_attribute = Hero.where("primary_attribute_id = ?", params[:id])
  end
end

app/controllers/role_controller.rb
class RoleController < ApplicationController
  def index
    @roles = Role.all
  end

  def show
    @hero_based_on_role = Hero.joins(:hero_roles).
                              where('hero_roles.role_id': params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heroes_helper.rb
module HeroesHelper
end

app/helpers/primary_attribute_helper.rb
module PrimaryAttributeHelper
end

app/helpers/role_helper.rb
module RoleHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        About Us | Gilbert Chiu
      </h1>
      <h2 class="subtitle">
        Description
      </h2>
    </div>
  </div>


</section>
<br>
<p>This project was consisted of api from <b><i><u>https://docs.opendota.com/</u></i></b>.</p>
<p>It was originally a JSON format API and then enventually i converted it to csv for me to be able to use it from csv approach.
The API has a lot of Dataset about dota from Hero, Hero Stats, Role, Pro player, players, matches, and etc...</p>

app/views/heroes/index.html.erb
<h3 class="title is-4">Heroes List</h3>
<!--<ul>
  <% @heroes.each do |hero| %>
    <li><%= hero.name %></li>
    <li><%= hero.localized_name %></li>
  <% end %>
</ul>-->

<table class="table">
  <thead>
    <tr>
      <th>Localized Name</th>
      <th>Name</th>
      <th>Attack Type</th>
      <th>Legs</th>
      <th>Roles</th>
      <th>Primary Attribute<th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <th>Name</th>
      <th>Localized Name</th>
      <th>Attack Type</th>
      <th>Legs</th>
      <th>Roles</th>
      <th>Primary Attribute<th>
    </tr>
  </tfoot>
  <tbody>
    <% @heroes.each do |hero| %>
    <tr>
      <td><%= link_to hero.localized_name, hero%></th>
      <td><%= hero.name %></th>
      <td><%= hero.attack_type %></th>
      <td><%= hero.legs %></th>
      <td><%= hero.roles_list %></th>
      <td><%= PrimaryAttribute.where("id = #{hero.primary_attribute_id}").first.name%></td>
    </tr>
    <% end %>
  </tbody>
</table>

<div>
  <%= link_to "Previous Page", heroes_path(page: @page - 1)%>
  <%= link_to "Next Page", heroes_path(page: @page + 1)%>
</div>

app/views/heroes/search.html.erb
<h1 class="title">Heroes found when searching for: <%= params[:keyword] %></h1>
<table class="table">
  <thead>
    <tr>
      <th>Localized Name</th>
      <th>Name</th>
      <th>Attack Type</th>
      <th>Legs</th>
      <th>Primary Attribute<th>
    </tr>
  </thead>
  <tbody>
    <% @heroes_searched.each do |hero| %>
    <tr>
      <td><%= link_to hero.localized_name, hero%></th>
      <td><%= hero.name %></th>
      <td><%= hero.attack_type %></th>
      <td><%= hero.legs %></th>
      <td><%= PrimaryAttribute.where("id = #{hero.primary_attribute_id}").first.name%></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/heroes/show.html.erb
<h1 class="title is-4"> <%= @hero.localized_name %> Description</h1>
<div class="card">
  <div class="card-image">
    <figure class="image is-2by1">
      <img src="http://cdn.dota2.com<%= @hero.img %>" alt="Hero Image">
    </figure>
  </div>
  <div class="card-content">
    <div class="media">
      <div class="media-left">
        <figure class="image is-48x48">
          <img src="http://cdn.dota2.com<%= @hero.icon %>" alt="Hero icon">
        </figure>
      </div>
      <div class="media-content">
        <p class="title is-4"><%= @hero.localized_name %></p>
        <p class="subtitle is-6"><%= @hero.name %></p>
      </div>
    </div>

    <div class="content">
      <b>Attack Type:</b> <%= @hero.attack_type %><br>
      <b>Legs:</b> <%= @hero.legs %><br>
      <b>Primary Attribute:</b> <%= PrimaryAttribute.where("id = #{@hero.primary_attribute_id}").first.name %><br>
      <b>Base Health:</b> <%= @hero.base_health %><br>
      <b>Base Health Regen:</b> <%= @hero.base_health_regen %><br>
      <b>Base Mana:</b> <%= @hero.base_mana %><br>
      <b>Base Mana Regen:</b> <%= @hero.base_mana_regen %><br>
      <b>Base Armor:</b> <%= @hero.base_armor %><br>
      <b>Base Movement Rate:</b> <%= @hero.base_mr %><br>
      <b>Base Attack Min:</b> <%= @hero.base_attack_min %><br>
      <b>Base Attack Max:</b> <%= @hero.base_attack_max %><br>
      <b>Base Str:</b> <%= @hero.base_str %><br>
      <b>Base Agi:</b> <%= @hero.base_agi %><br>
      <b>Base Int:</b> <%= @hero.base_int %><br>
      <b>Str Gain:</b> <%= @hero.str_gain %><br>
      <b>Agi Gain:</b> <%= @hero.agi_gain %><br>
      <b>Int Gain:</b> <%= @hero.int_gain %><br>
      <b>Projectile Speed:</b> <%= @hero.projectile_speed %><br>
      <b>Attack Rate:</b> <%= @hero.attack_rate %><br>
      <b>Move Speed:</b> <%= @hero.move_speed %><br>
      <b>Turn:</b> <%= @hero.turn_rate %><br>
      <b>CM Enable:</b> <%= @hero.cm_enabled %><br>

    </div>
  </div>
</div>

<div class="navbar-item">
  <%= link_to "Back to Heroes", heroes_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Project | Dota API</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
  <nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="https://bulma.io">
      <img src="https://1000logos.net/wp-content/uploads/2019/03/Dota-2-Logo.png" width="112" height="28">
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <div class="navbar-item">
        <%= link_to "Home", welcome_index_path %>
      </div>

      <div class="navbar-item">
        <%= link_to "About", about_index_path %>
      </div>

      <div class="navbar-item">
        <%= link_to "Heroes", heroes_path %>
      </div>

      <div class="navbar-item">
        <%= link_to "Primary Attributes", primary_attribute_index_path %>
      </div>

      <div class="navbar-item">
        <%= link_to "Roles", role_index_path %>
      </div>
    </div>
  </div>
</nav>
  <section class="section">
    <div class="container">
      <h1 class="title">
      Dota2 Heroes API | Gilbert Gulliver Chiu PROJECT
      </h1>

      <%= form_with(url: search_heroes_path, method: :get, local: true) do %>
        <div class="field is-grouped mb-5">
          <div class="control is-expanded">
            <%= text_field_tag(:keywords, nil, class: "input", placeholder: 'Search for heroes')%>
          </div>
          <div class="control">
            <%= submit_tag("Search", class: "button is-primary")%>
          </div>
        </div>
      <% end %>

      <%= yield %>
      <hr/>
      <p class="subtitle">
        This website was create with <strong>Bulma</strong>!
      </p>
    </div>
  </section>

  </body>
</html>

app/views/primary_attribute/index.html.erb
<h3 class="title is-4">Primary Attribute List</h3>
<table class="table">
  <thead>
    <tr>
      <th>Attribute</th>
      <th>Hero Count</th>
      <th>Action</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <th>Attribute</th>
      <th>Hero Count</th>
      <th>Action</th>
    </tr>
  </tfoot>
  <tbody>
    <% @primary_attributes.each do |attr| %>
    <tr>
      <td><%= attr.name %></th>
      <td><%= Hero.where("primary_attribute_id = #{attr.id}").count%></th>
      <td><%= link_to "View All Hero", "primary_attribute/#{attr.id}" %></th>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/primary_attribute/show.html.erb
<h1 class="title is-4">View hero based on <%= PrimaryAttribute.find(params[:id]).name%></h1>
<table class="table">
  <thead>
    <tr>
      <th>Localized Name</th>
      <th>Name</th>
      <th>Attack Type</th>
      <th>Legs</th>
      <th>Primary Attribute<th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <th>Name</th>
      <th>Localized Name</th>
      <th>Attack Type</th>
      <th>Legs</th>
      <th>Roles</th>
      <th>Primary Attribute<th>
    </tr>
  </tfoot>
  <tbody>
    <% @hero_based_on_attribute.each do |hero| %>
    <tr>
      <td><%= link_to hero.localized_name, hero%></th>
      <td><%= hero.name %></th>
      <td><%= hero.attack_type %></th>
      <td><%= hero.legs %></th>
      <td><%= hero.roles_list %></th>
      <td><%= PrimaryAttribute.where("id = #{hero.primary_attribute_id}").first.name%></td>

    </tr>
    <% end %>
  </tbody>
</table>
<div>

<div class="navbar-item">
  <%= link_to "Go Back", primary_attribute_index_path %>
</div>

app/views/role/index.html.erb
<h3 class="title is-4">Role List</h3>
<table class="table">
  <thead>
    <tr>
      <th>Role</th>
      <th>Hero Count</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @roles.each do |attr| %>
    <tr>
      <td><%= attr.name %></th>
      <td><%= HeroRole.where("role_id = #{attr.id}").count%></th>
      <td><%= link_to "View All Hero", "#{attr.id}" %></th>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/role/show.html.erb
<h1 class="title is-4">Heroes with <%= Role.find(params[:id]).name%> Role</h1>
<table class="table">
  <thead>
    <tr>
      <th>Localized Name</th>
      <th>Name</th>
      <th>Attack Type</th>
      <th>Primary Attribute<th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <th>Name</th>
      <th>Localized Name</th>
      <th>Roles</th>
      <th>Primary Attribute<th>
    </tr>
  </tfoot>
  <tbody>
    <% @hero_based_on_role.each do |hero| %>
    <tr>
      <td><%= link_to hero.localized_name, hero%></th>
      <td><%= hero.name %></th>
      <td><%= hero.roles_list %></th>
      <td><%= PrimaryAttribute.where("id = #{hero.primary_attribute_id}").first.name%></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/welcome/index.html.erb
<img src="https://dmarket.com/blog/best-dota2-wallpapers/dota2heroes7_hu3b1dceb244ec3fefbad73471cde2e900_222198_1920x1080_resize_q75_lanczos.jpg">

<h1>Dota 2 is a multiplayer online battle arena (MOBA) video game developed and published by Valve. The game is a sequel to Defense of the Ancients (DotA), which was a community-created mod for Blizzard Entertainment's Warcraft III: Reign of Chaos and its expansion pack, The Frozen Throne. Dota 2 is played in matches between two teams of five players, with each team occupying and defending their own separate base on the map. Each of the ten players independently controls a powerful character, known as a "hero", who all have unique abilities and differing styles of play. During a match players collect experience points and items for their heroes to successfully defeat the opposing team's heroes in player versus player combat. A team wins by being the first to destroy the other team's "Ancient", a large structure located within their base.</h1>